manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: dannygrob
      url-base: https://github.com/dannygrob
  projects:
    - name: zmk
      revision: pcf8575-support
      url: https://github.com/dannygrob/zmk-pcf8575
      import: app/west.yml
  self:
    path: config